name: Link Checker

on:
  schedule:
    # 毎日 朝 6 時に実行する場合は '0 6 * * *'
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # CSVファイルをコミット＆プッシュするため

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python scripts/crawl_links.py

      - name: Commit & Push broken_links.csv
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add broken_links.csv
          git commit -m "Update broken_links.csv [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
